#!/bin/bash
# =============================================================================
# TurboQuant headless server startup script
# Generated by lib-engine.sh from wrapper-start.sh.tpl
# Ne pas modifier — regenerer via: ./inference-servers/turboquant/setup.sh
# =============================================================================

LOG_DIR="{{LOG_DIR}}"
CONFIG_DIR="$(dirname "$(readlink -f "$0")")/../inference-servers/turboquant/configs"

# Config par defaut (peut etre overridee par env var TURBOQUANT_CONFIG)
CONFIG_FILE="${TURBOQUANT_CONFIG:-{{CONFIG_DIR}}/{{MODEL_CONFIG}}}"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $*" >> "$LOG_DIR/turboquant.log"
}

log "Starting TurboQuant server..."

# Charger la config modele
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
    log "Config loaded: $CONFIG_FILE"
else
    log "ERROR: Config not found: $CONFIG_FILE"
    echo "ERROR: Config not found: $CONFIG_FILE" >> "$LOG_DIR/turboquant.err"
    exit 1
fi

# Lever la limite GPU (obligatoire pour les gros modeles)
if [[ -n "${GPU_WIRED_MB:-}" ]] && [[ "$GPU_WIRED_MB" -gt 0 ]]; then
    log "Setting GPU wired limit: ${GPU_WIRED_MB} MB"
    sudo sysctl iogpu.wired_limit_mb="$GPU_WIRED_MB" >> "$LOG_DIR/turboquant.log" 2>> "$LOG_DIR/turboquant.err" || true
fi

# Verifier que le modele existe
if [[ ! -f "$MODEL_PATH" ]]; then
    log "ERROR: Model not found: $MODEL_PATH"
    echo "ERROR: Model not found: $MODEL_PATH" >> "$LOG_DIR/turboquant.err"
    exit 1
fi

log "Model: $MODEL_PATH"
log "KV cache: keys=${CACHE_TYPE_K}, values=${CACHE_TYPE_V}"
log "Context: ${CONTEXT_SIZE}, Threads: ${THREADS}"
log "Port: {{PORT}}, Bind: {{BIND}}"

# Lancer llama-server avec tous les parametres turbo
exec {{ENGINE_BIN}} \
    -m "$MODEL_PATH" \
    --cache-type-k "${CACHE_TYPE_K}" \
    --cache-type-v "${CACHE_TYPE_V}" \
    -c "${CONTEXT_SIZE}" \
    --port {{PORT}} \
    --host {{BIND}} \
    -fa 1 \
    -ngl 99 \
    -t "${THREADS}" \
    --no-mmap \
    --chat-template "${CHAT_TEMPLATE}"
