"""pf anchor management for engine firewalls.

Ports ``lib-engine.sh:540-622`` (``engine_setup_firewall`` /
``engine_remove_firewall``) to Python.

Concretely we generate a small pf anchor file under ``/etc/pf.anchors/`` that
allows the engine port from localhost + RFC1918 subnets and blocks everything
else, then we add a single ``anchor "<name>" all`` line to ``/etc/pf.conf``
and reload pf. ``com.asiai.*`` is the only label pattern accepted, paired with
the strict-scope sudoers rule that whitelists ``/sbin/pfctl -f
/etc/pf.anchors/com.asiai.*`` only.

Atomic write
------------
We write the anchor file via ``sudo tee`` from a stdin buffer (no shell heredoc
race) and validate the syntax with ``pfctl -nf <file>`` before activating it.
The Bash version skipped the validation step and would silently push a broken
anchor into pf.conf.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from ais_core.io import secure_staging_dir
from ais_core.manifest import ANCHOR_NAME_RE, EngineManifest

PF_CONF_PATH = "/etc/pf.conf"
PF_ANCHORS_DIR = "/etc/pf.anchors"

# RFC1918 private subnets — the only sources allowed by default.
DEFAULT_SUBNETS: tuple[str, ...] = (
    "192.168.0.0/16",
    "10.0.0.0/8",
    "172.16.0.0/12",
)


class FirewallError(RuntimeError):
    """Raised when an anchor cannot be written, validated, or activated."""


def anchor_path(manifest: EngineManifest) -> str:
    return f"{PF_ANCHORS_DIR}/{manifest.firewall.anchor_name}"


def build_anchor_content(
    manifest: EngineManifest,
    *,
    subnets: tuple[str, ...] = DEFAULT_SUBNETS,
) -> str:
    """Render the pf anchor body.

    Pure function — no I/O, no validation, just text. The result is fed to
    ``pfctl -nf`` for syntax validation before any real install.
    """
    if not ANCHOR_NAME_RE.match(manifest.firewall.anchor_name):
        raise FirewallError(
            f"Anchor name {manifest.firewall.anchor_name!r} must match com.asiai.<engine>"
        )
    if not subnets:
        raise FirewallError("subnets is empty; refusing to write a wide-open anchor")

    port = manifest.network.port
    subnet_list = ", ".join(subnets)
    return (
        f"# {manifest.display} firewall rules — generated by asiai-inference-server\n"
        f"# Allow LAN-only access on port {port}\n"
        "\n"
        f"pass in quick on lo0 proto tcp to any port {port} keep state\n"
        f"pass in quick inet proto tcp from {{ {subnet_list} }} "
        f"to any port {port} flags S/SA keep state\n"
        f"block in quick inet proto tcp to any port {port}\n"
    )


def validate_anchor(anchor_text: str) -> None:
    """Run ``pfctl -nf -`` against the anchor body. Raises FirewallError on failure."""
    proc = subprocess.run(
        ["sudo", "/sbin/pfctl", "-nf", "-"],
        input=anchor_text,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        raise FirewallError(f"pfctl rejected anchor: {proc.stderr.strip() or proc.stdout.strip()}")


def install_anchor(
    manifest: EngineManifest,
    *,
    subnets: tuple[str, ...] = DEFAULT_SUBNETS,
    dry_run: bool = False,
) -> str:
    """Render, validate, and activate the pf anchor for this engine.

    Returns the absolute path of the installed anchor file.

    Sequence:
      1. Render content (pure).
      2. Validate via ``pfctl -nf -`` (fail fast on syntax errors).
      3. Write to a tmpfile, ``sudo /bin/mv`` to ``/etc/pf.anchors/<name>``.
      4. Append ``anchor "<name>" all`` to ``/etc/pf.conf`` if absent.
      5. ``sudo /sbin/pfctl -f /etc/pf.conf`` to load the new ruleset.
    """
    if not manifest.firewall.supported:
        raise FirewallError(
            f"{manifest.name}: firewall.supported=false — refusing to install anchor"
        )

    content = build_anchor_content(manifest, subnets=subnets)
    dst = anchor_path(manifest)

    if dry_run:
        print(f"--- anchor {dst} ---")
        print(content, end="")
        print("--- end anchor ---")
        return dst

    validate_anchor(content)

    with secure_staging_dir() as staging:
        tmp_path = staging / f"{manifest.firewall.anchor_name}.anchor"
        tmp_path.write_text(content, encoding="utf-8")
        try:
            subprocess.run(["sudo", "/bin/mkdir", "-p", PF_ANCHORS_DIR], check=True)
            subprocess.run(["sudo", "/bin/mv", str(tmp_path), dst], check=True)
            subprocess.run(["sudo", "/usr/sbin/chown", "root:wheel", dst], check=True)
            subprocess.run(["sudo", "/bin/chmod", "644", dst], check=True)
        except subprocess.CalledProcessError as e:
            raise FirewallError(f"Failed to install anchor {dst}: {e}") from e

    _ensure_anchor_in_pf_conf(manifest.firewall.anchor_name)
    _reload_pf()
    return dst


def remove_anchor(manifest: EngineManifest, *, dry_run: bool = False) -> bool:
    """Delete the anchor file and the matching line from ``/etc/pf.conf``.

    Returns True if anything was changed, False if the anchor was already gone.
    """
    dst = anchor_path(manifest)
    name = manifest.firewall.anchor_name
    changed = False

    if Path(dst).exists():
        if dry_run:
            print(f"[dry-run] sudo /bin/rm -f {dst}")
        else:
            subprocess.run(["sudo", "/bin/rm", "-f", dst], check=True)
        changed = True

    pf_conf_text = _read_pf_conf()
    line_re = re.compile(rf'^anchor\s+"{re.escape(name)}"\s+all\s*$', re.MULTILINE)
    if line_re.search(pf_conf_text):
        new_text = line_re.sub("", pf_conf_text)
        # Collapse the blank line that the substitution leaves behind.
        new_text = re.sub(r"\n{3,}", "\n\n", new_text)
        if dry_run:
            print(f"[dry-run] would rewrite {PF_CONF_PATH} (1 anchor line removed)")
        else:
            _atomic_write_pf_conf(new_text)
            _reload_pf()
        changed = True

    return changed


def _read_pf_conf() -> str:
    try:
        return Path(PF_CONF_PATH).read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def _ensure_anchor_in_pf_conf(name: str) -> None:
    """Append ``anchor "<name>" all`` to /etc/pf.conf if not already present."""
    text = _read_pf_conf()
    expected = f'anchor "{name}" all'
    if any(line.strip() == expected for line in text.splitlines()):
        return
    new_text = text.rstrip() + f"\n{expected}\n"
    _atomic_write_pf_conf(new_text)


def _atomic_write_pf_conf(new_text: str) -> None:
    with secure_staging_dir() as staging:
        tmp_path = staging / "pf.conf"
        tmp_path.write_text(new_text, encoding="utf-8")
        try:
            subprocess.run(["sudo", "/bin/mv", str(tmp_path), PF_CONF_PATH], check=True)
            subprocess.run(["sudo", "/usr/sbin/chown", "root:wheel", PF_CONF_PATH], check=True)
            subprocess.run(["sudo", "/bin/chmod", "644", PF_CONF_PATH], check=True)
        except subprocess.CalledProcessError as e:
            raise FirewallError(f"Failed to update {PF_CONF_PATH}: {e}") from e


def _reload_pf() -> None:
    """Reload pf rules. Best-effort: pf may already be enabled."""
    subprocess.run(
        ["sudo", "/sbin/pfctl", "-f", PF_CONF_PATH],
        check=False,
        capture_output=True,
    )
    subprocess.run(["sudo", "/sbin/pfctl", "-e"], check=False, capture_output=True)
