"""Engine manifest loader and validator.

A manifest declares everything we need to install, configure, and supervise an
inference engine: its binary candidates, its LaunchDaemon plist, its network
endpoint, its firewall anchor, and its environment. Manifests live as TOML
files under ``data/engine_manifests/`` and are loaded into typed dataclasses
here.

Why TOML
--------
``tomllib`` is stdlib in Python 3.11+, so we keep our zero-dependency promise.
TOML reads cleaner than JSON (comments, no trailing-comma traps) for files
edited by humans.

Why bundled, not user-editable
------------------------------
Manifests describe the engine itself (Ollama is Ollama everywhere), so they
ship with the package. User overrides go in ``~/.config/asiai-inference-server/``
in v0.2+ — never in the bundled manifests.

Plist label policy
------------------
Plist labels MUST match ``^com\\.asiai\\.[a-z0-9-]+$``. This pairs with the
strict-scope sudoers rule generated by :mod:`ais_core.sudoers` (NOPASSWD only
on ``com.asiai.*`` LaunchDaemons). The legacy openclaw plists (``com.ollama.serve``,
``com.lmstudio.server``, ``com.omlx.server``) keep working because they are
separate plist files; an ``aisctl engine install`` writes a fresh
``com.asiai.<engine>.plist`` and ignores the legacy one.
"""

from __future__ import annotations

import os
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

PLIST_LABEL_RE = re.compile(r"^com\.asiai\.[a-z0-9-]+$")
ANCHOR_NAME_RE = re.compile(r"^com\.asiai\.[a-z0-9-]+$")

# process_pattern is passed verbatim to ``pgrep -f`` / ``pkill -f``, which
# interpret it as an extended regex over the full cmdline of every running
# process. A lax pattern (e.g. ``"."``) would match everything on the system
# and turn ``aisctl engine stop`` into a fleet-wide kill. We therefore require
# a literal-looking string: alphanumerics plus a small set of safe punctuation
# (slash, underscore, dash, dot, space) — none of which carry regex meaning
# *as a whole class*, and a leading letter so a manifest can't ship ``"."``.
PROCESS_PATTERN_RE = re.compile(r"^[A-Za-z](?:[A-Za-z0-9/_. -]*[A-Za-z0-9])?$")


class ManifestError(ValueError):
    """Raised when a manifest is malformed or violates a hard constraint."""


@dataclass(frozen=True)
class BinarySpec:
    candidates: tuple[str, ...]
    process_pattern: str
    program_args: tuple[str, ...] = ()
    builds_from_source: bool = False

    def resolve(self) -> str | None:
        """Return the first existing binary candidate, expanding ``~``.

        Returns None if none of the candidates exist on disk. Callers decide
        whether that's a fatal install precondition or a soft check.
        """
        for c in self.candidates:
            expanded = os.path.expanduser(c)
            if Path(expanded).is_file():
                return expanded
        return None


@dataclass(frozen=True)
class PlistSpec:
    name: str
    throttle_interval: int
    timeout: int


@dataclass(frozen=True)
class NetworkSpec:
    port: int
    bind: str
    health_endpoint: str
    health_timeout: int

    @property
    def health_url(self) -> str:
        host = self.bind or "127.0.0.1"
        return f"http://{host}:{self.port}{self.health_endpoint}"


@dataclass(frozen=True)
class FirewallSpec:
    supported: bool
    anchor_name: str


@dataclass(frozen=True)
class LogSpec:
    dir: str
    stdout: str
    stderr: str

    @property
    def expanded_dir(self) -> str:
        """Expand ``~`` to the current user's home (manifest stores tilde paths)."""
        return os.path.expanduser(self.dir.rstrip("/"))

    @property
    def stdout_path(self) -> str:
        return f"{self.expanded_dir}/{self.stdout}"

    @property
    def stderr_path(self) -> str:
        return f"{self.expanded_dir}/{self.stderr}"


@dataclass(frozen=True)
class WrapperSpec:
    needed: bool
    install_path: str | None = None
    template: str | None = None


@dataclass(frozen=True)
class EngineManifest:
    name: str
    display: str
    binary: BinarySpec
    plist: PlistSpec
    network: NetworkSpec
    firewall: FirewallSpec
    logs: LogSpec
    wrapper: WrapperSpec
    env_vars: tuple[str, ...] = ()
    options: dict[str, object] = field(default_factory=dict)


def _bundled_manifest_dir() -> Path:
    """Locate the ``engine_manifests`` directory in either install layout.

    Wheel install copies ``data/engine_manifests/`` next to the package via
    ``[tool.hatch.build.targets.wheel.force-include]`` (see pyproject.toml).
    Editable install (``pip install -e .``) keeps it at the repo root.
    """
    here = Path(__file__).resolve().parent  # src/ais_core

    bundled = here / "data" / "engine_manifests"
    if bundled.is_dir():
        return bundled

    repo_root = here.parent.parent  # src/ais_core -> src -> repo
    editable = repo_root / "data" / "engine_manifests"
    if editable.is_dir():
        return editable

    raise FileNotFoundError(
        f"engine_manifests/ not found under {bundled} or {editable}; "
        "install layout is broken"
    )


def list_manifests() -> list[str]:
    """Return the names of every bundled manifest, sorted for reproducibility."""
    return sorted(p.stem for p in _bundled_manifest_dir().glob("*.toml"))


def load_manifest(name: str) -> EngineManifest:
    """Load and validate a single manifest by name (e.g. ``"ollama"``)."""
    path = _bundled_manifest_dir() / f"{name}.toml"
    if not path.is_file():
        raise FileNotFoundError(f"No manifest for engine {name!r} at {path}")

    with path.open("rb") as f:
        raw = tomllib.load(f)

    return _from_dict(raw, source=str(path))


def _from_dict(raw: dict, *, source: str) -> EngineManifest:
    try:
        binary_raw = raw["binary"]
        plist_raw = raw["plist"]
        net_raw = raw["network"]
        fw_raw = raw["firewall"]
        log_raw = raw["logs"]
        wrap_raw = raw["wrapper"]
        env_raw = raw.get("environment", {})
        opt_raw = raw.get("options", {})

        manifest = EngineManifest(
            name=raw["name"],
            display=raw["display"],
            binary=BinarySpec(
                candidates=tuple(binary_raw["candidates"]),
                process_pattern=binary_raw["process_pattern"],
                program_args=tuple(binary_raw.get("program_args", [])),
                builds_from_source=bool(binary_raw.get("builds_from_source", False)),
            ),
            plist=PlistSpec(
                name=plist_raw["name"],
                throttle_interval=int(plist_raw["throttle_interval"]),
                timeout=int(plist_raw["timeout"]),
            ),
            network=NetworkSpec(
                port=int(net_raw["port"]),
                bind=str(net_raw.get("bind", "")),
                health_endpoint=net_raw["health_endpoint"],
                health_timeout=int(net_raw["health_timeout"]),
            ),
            firewall=FirewallSpec(
                supported=bool(fw_raw["supported"]),
                anchor_name=fw_raw["anchor_name"],
            ),
            logs=LogSpec(
                dir=log_raw["dir"],
                stdout=log_raw["stdout"],
                stderr=log_raw["stderr"],
            ),
            wrapper=WrapperSpec(
                needed=bool(wrap_raw["needed"]),
                install_path=wrap_raw.get("install_path"),
                template=wrap_raw.get("template"),
            ),
            env_vars=tuple(env_raw.get("vars", [])),
            options=dict(opt_raw),
        )
    except KeyError as e:
        raise ManifestError(f"{source}: missing required key {e}") from e

    _validate(manifest, source=source)
    return manifest


def _validate(m: EngineManifest, *, source: str) -> None:
    if not PLIST_LABEL_RE.match(m.plist.name):
        raise ManifestError(
            f"{source}: plist.name {m.plist.name!r} does not match com.asiai.<engine>; "
            "this is required so the strict-scope sudoers rule still applies."
        )

    if not ANCHOR_NAME_RE.match(m.firewall.anchor_name):
        raise ManifestError(
            f"{source}: firewall.anchor_name {m.firewall.anchor_name!r} must match "
            "com.asiai.<engine> so pfctl wildcard sudoers stays scoped."
        )

    if not (1 <= m.network.port <= 65535):
        raise ManifestError(f"{source}: network.port {m.network.port} out of range")

    if not m.network.health_endpoint.startswith("/"):
        raise ManifestError(
            f"{source}: network.health_endpoint must start with '/', "
            f"got {m.network.health_endpoint!r}"
        )

    if m.wrapper.needed and not m.wrapper.install_path:
        raise ManifestError(
            f"{source}: wrapper.needed=true but wrapper.install_path is empty"
        )

    if not m.binary.candidates:
        raise ManifestError(f"{source}: binary.candidates is empty")

    if not PROCESS_PATTERN_RE.match(m.binary.process_pattern):
        raise ManifestError(
            f"{source}: binary.process_pattern {m.binary.process_pattern!r} contains "
            "characters that pgrep/pkill -f would interpret as regex metacharacters; "
            "only alphanumerics, '/', '_', '-', '.', and spaces are allowed, with "
            "a leading letter."
        )

    for var in m.env_vars:
        if "=" not in var:
            raise ManifestError(
                f"{source}: environment.vars entry {var!r} must be 'KEY=VALUE'"
            )


def is_valid_plist_label(label: str) -> bool:
    """Public predicate used by ais_core.sudoers and ais_core.lifecycle."""
    return bool(PLIST_LABEL_RE.match(label))
