"""Engine manifest loader and validator.

A manifest declares everything we need to install, configure, and supervise an
inference engine: its binary candidates, its LaunchDaemon plist, its network
endpoint, its firewall anchor, and its environment. Manifests live as TOML
files under ``data/engine_manifests/`` and are loaded into typed dataclasses
here.

Why TOML
--------
``tomllib`` is stdlib in Python 3.11+, so we keep our zero-dependency promise.
TOML reads cleaner than JSON (comments, no trailing-comma traps) for files
edited by humans.

Bundled defaults + user overrides
---------------------------------
Manifests describe the engine itself (Ollama is Ollama everywhere), so the
baseline ships with the package. Users who want to add their own engine
instances (e.g. ``llamacpp-aux-6`` for a sixth auxiliary slot) or override
the bundled tuning of a preset drop their TOML into the XDG user config
directory:

    $XDG_CONFIG_HOME/asiai-inference-server/engine_manifests/<name>.toml
    $XDG_CONFIG_HOME/asiai-inference-server/engine_manifests/presets/<preset>.toml

(User presets mirror the bundled package layout: presets live next to the
manifests they tune. Up to v0.2 they were read from ``presets/`` at the
config root instead — that location is no longer scanned, and any TOML
left there triggers a loud warning naming the file and the new path.)

The override path is ``~/.config/asiai-inference-server/`` by default and
can be relocated wholesale via the ``ASIAI_USER_CONFIG_DIR`` environment
variable (testing, sandboxed installs).

When a user manifest or preset shares its name with a bundled file, the
user version wins and a warning is logged at load time so operators see
the override happening.

Plist label policy
------------------
Plist labels MUST match ``^com\\.asiai\\.[a-z0-9-]+$``. This pairs with the
strict-scope sudoers rule generated by :mod:`ais_core.sudoers` (NOPASSWD only
on ``com.asiai.*`` LaunchDaemons). The legacy openclaw plists (``com.ollama.serve``,
``com.lmstudio.server``, ``com.omlx.server``) keep working because they are
separate plist files; an ``aisctl engine install`` writes a fresh
``com.asiai.<engine>.plist`` and ignores the legacy one.
"""

from __future__ import annotations

import logging
import os
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

PLIST_LABEL_RE = re.compile(r"^com\.asiai\.[a-z0-9-]+$")
ANCHOR_NAME_RE = re.compile(r"^com\.asiai\.[a-z0-9-]+$")

# process_pattern is passed verbatim to ``pgrep -f`` / ``pkill -f``, which
# interpret it as an extended regex over the full cmdline of every running
# process. A lax pattern (e.g. ``"."``) would match everything on the system
# and turn ``aisctl engine stop`` into a fleet-wide kill. We therefore require
# a literal-looking string: alphanumerics plus a small set of safe punctuation
# (slash, underscore, dash, dot, space) — none of which carry regex meaning
# *as a whole class*, and a leading letter so a manifest can't ship ``"."``.
PROCESS_PATTERN_RE = re.compile(r"^[A-Za-z](?:[A-Za-z0-9/_. -]*[A-Za-z0-9])?$")


class ManifestError(ValueError):
    """Raised when a manifest is malformed or violates a hard constraint."""


@dataclass(frozen=True)
class BinarySpec:
    candidates: tuple[str, ...]
    process_pattern: str
    program_args: tuple[str, ...] = ()
    builds_from_source: bool = False
    # Optional model file path injected as ``--model <path>`` in ProgramArguments.
    # Currently used by engines that bind to a single model at launch time
    # (e.g. llama-server: one instance = one GGUF). Tilde-expanded at plist
    # generation time. Convention: user-managed symlink at the target so
    # the manifest stays Mac-portable (e.g. ``~/llms/gguf/active.gguf``).
    model_path: str | None = None
    # Optional chat template file path injected as ``--chat-template-file <path>``.
    # Used to override a model's embedded Jinja template (e.g. froggeric fixed
    # templates for Qwen3.6 that replace ``|items`` -- a Python-only filter --
    # with C++-safe equivalents that minijinja can parse). Same tilde-expansion
    # contract as ``model_path``.
    template_path: str | None = None
    # Optional multimodal projection (mmproj) file path injected as
    # ``--mmproj <path>``. Used by vision-enabled llama-server instances
    # to load the CLIP/vision encoder companion to the text-side GGUF.
    # Same tilde-expansion contract as ``model_path`` — preset writers
    # should use this field rather than passing ``--mmproj ~/...`` in
    # ``program_args``, where the tilde would not be expanded.
    mmproj_path: str | None = None

    def resolve(self) -> str | None:
        """Return the first existing binary candidate, expanding ``~``.

        Returns None if none of the candidates exist on disk. Callers decide
        whether that's a fatal install precondition or a soft check.
        """
        for c in self.candidates:
            expanded = os.path.expanduser(c)
            if Path(expanded).is_file():
                return expanded
        return None


@dataclass(frozen=True)
class PlistSpec:
    name: str
    throttle_interval: int
    timeout: int


@dataclass(frozen=True)
class NetworkSpec:
    port: int
    bind: str
    health_endpoint: str
    health_timeout: int
    gen_check: bool = False

    @property
    def health_url(self) -> str:
        # Like gen_url, the probe runs on the host itself: a 0.0.0.0 bind
        # answers on loopback, and 0.0.0.0 is not a connectable address.
        host = "127.0.0.1" if self.bind in ("", "0.0.0.0") else self.bind
        return f"http://{host}:{self.port}{self.health_endpoint}"

    @property
    def gen_url(self) -> str:
        """OpenAI-compatible chat endpoint used by the generation probe.

        Always targets loopback: the probe runs on the host itself and must
        not depend on the bind address (0.0.0.0 binds answer on 127.0.0.1).
        """
        return f"http://127.0.0.1:{self.port}/v1/chat/completions"


@dataclass(frozen=True)
class FirewallSpec:
    supported: bool
    anchor_name: str


@dataclass(frozen=True)
class LogSpec:
    dir: str
    stdout: str
    stderr: str

    @property
    def expanded_dir(self) -> str:
        """Expand ``~`` to the current user's home (manifest stores tilde paths)."""
        return os.path.expanduser(self.dir.rstrip("/"))

    @property
    def stdout_path(self) -> str:
        return f"{self.expanded_dir}/{self.stdout}"

    @property
    def stderr_path(self) -> str:
        return f"{self.expanded_dir}/{self.stderr}"


@dataclass(frozen=True)
class WrapperSpec:
    needed: bool
    install_path: str | None = None
    template: str | None = None


@dataclass(frozen=True)
class EngineManifest:
    name: str
    display: str
    binary: BinarySpec
    plist: PlistSpec
    network: NetworkSpec
    firewall: FirewallSpec
    logs: LogSpec
    wrapper: WrapperSpec
    env_vars: tuple[str, ...] = ()
    options: dict[str, object] = field(default_factory=dict)


def _bundled_manifest_dir() -> Path:
    """Locate the ``engine_manifests`` directory in either install layout.

    Wheel install copies ``data/engine_manifests/`` next to the package via
    ``[tool.hatch.build.targets.wheel.force-include]`` (see pyproject.toml).
    Editable install (``pip install -e .``) keeps it at the repo root.
    """
    here = Path(__file__).resolve().parent  # src/ais_core

    bundled = here / "data" / "engine_manifests"
    if bundled.is_dir():
        return bundled

    repo_root = here.parent.parent  # src/ais_core -> src -> repo
    editable = repo_root / "data" / "engine_manifests"
    if editable.is_dir():
        return editable

    raise FileNotFoundError(
        f"engine_manifests/ not found under {bundled} or {editable}; install layout is broken"
    )


def _user_config_dir() -> Path:
    """Resolve the XDG user-config directory for asiai-inference-server.

    Order of precedence:

    1. ``ASIAI_USER_CONFIG_DIR`` environment variable — full override of the
       whole user-config tree (used by tests, sandboxed installs, multi-host
       layouts).
    2. ``XDG_CONFIG_HOME/asiai-inference-server`` if ``XDG_CONFIG_HOME`` is set.
    3. ``~/.config/asiai-inference-server`` (POSIX default).
    """
    override = os.environ.get("ASIAI_USER_CONFIG_DIR")
    if override:
        return Path(override).expanduser()
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return Path(xdg).expanduser() / "asiai-inference-server"
    return Path("~/.config/asiai-inference-server").expanduser()


def _user_manifest_dir() -> Path:
    return _user_config_dir() / "engine_manifests"


def _user_preset_dir() -> Path:
    """The single user preset location: ``engine_manifests/presets/``.

    Mirrors the bundled package layout (presets live next to the manifests
    they tune) and is what operators create spontaneously.
    """
    return _user_manifest_dir() / "presets"


def _legacy_preset_dir() -> Path:
    """Pre-v0.3 user preset location (``presets/`` at the config root).

    No longer scanned — kept only so :func:`_warn_legacy_presets` can tell
    operators their files moved out of resolution.
    """
    return _user_config_dir() / "presets"


def _warn_legacy_presets() -> None:
    """Shout if preset TOMLs linger in the dead pre-v0.3 location.

    Without this, an operator upgrading from v0.2 would get 'unknown preset'
    (or worse, silently fall back to a bundled preset of the same name) with
    no hint that their files simply stopped being read.
    """
    legacy = _legacy_preset_dir()
    if not legacy.is_dir():
        return
    stale = sorted(p.name for p in legacy.glob("*.toml"))
    if stale:
        logger.warning(
            "ignoring %d preset(s) in deprecated location %s (%s); "
            "user presets are read from %s — move the files there",
            len(stale),
            legacy,
            ", ".join(stale),
            _user_preset_dir(),
        )


def list_manifests() -> list[str]:
    """Return the names of every discoverable engine manifest, sorted.

    Union of bundled manifests (shipped with the package) and any user
    manifests dropped in the XDG user-config directory. A user manifest
    that shares a stem with a bundled one is silently included once in
    the returned set — the user version wins at ``load_manifest()`` time
    (with a warning log).
    """
    names = {p.stem for p in _bundled_manifest_dir().glob("*.toml")}
    user_dir = _user_manifest_dir()
    if user_dir.is_dir():
        names |= {p.stem for p in user_dir.glob("*.toml")}
    return sorted(names)


def list_presets() -> list[str]:
    """Return the names of every discoverable preset, sorted.

    Presets are full self-contained manifests tuned for a specific model
    plus use case. Bundled presets live under ``data/engine_manifests/presets/``
    in the package and serve as documented examples (see the ``README.md``
    next to them). Users add their own under
    ``$XDG_CONFIG_HOME/asiai-inference-server/engine_manifests/presets/`` —
    these are picked up automatically and override any bundled preset of
    the same name.
    """
    _warn_legacy_presets()
    bundled = _bundled_manifest_dir() / "presets"
    names = set()
    if bundled.is_dir():
        names |= {p.stem for p in bundled.glob("*.toml")}
    user_dir = _user_preset_dir()
    if user_dir.is_dir():
        names |= {p.stem for p in user_dir.glob("*.toml")}
    return sorted(names)


def _find_manifest_path(name: str) -> Path | None:
    """User dir first (override semantics), bundled dir second."""
    user = _user_manifest_dir() / f"{name}.toml"
    if user.is_file():
        bundled = _bundled_manifest_dir() / f"{name}.toml"
        if bundled.is_file():
            logger.warning(
                "user manifest %s overrides bundled manifest (user=%s, bundled=%s)",
                name,
                user,
                bundled,
            )
        return user
    bundled = _bundled_manifest_dir() / f"{name}.toml"
    if bundled.is_file():
        return bundled
    return None


def _find_preset_path(preset: str) -> Path | None:
    """User dir first (override semantics), bundled dir second."""
    _warn_legacy_presets()
    bundled = _bundled_manifest_dir() / "presets" / f"{preset}.toml"
    user = _user_preset_dir() / f"{preset}.toml"
    if user.is_file():
        if bundled.is_file():
            logger.warning(
                "user preset %s overrides bundled preset (user=%s, bundled=%s)",
                preset,
                user,
                bundled,
            )
        return user
    if bundled.is_file():
        return bundled
    return None


def manifest_source_path(name: str, preset: str | None = None) -> Path | None:
    """The TOML file that ``load_manifest(name, preset=preset)`` would read.

    None when nothing resolves. Exposed for callers that need to fingerprint
    the installed configuration (install records, drift detection).
    """
    if preset is not None:
        return _find_preset_path(preset)
    return _find_manifest_path(name)


def preset_search_dirs() -> tuple[Path, ...]:
    """Every directory scanned for presets, in precedence order.

    User dir first, bundled package dir last. Exposed so CLI error messages
    can show the operator the real resolved paths that were searched.
    """
    return (_user_preset_dir(), _bundled_manifest_dir() / "presets")


def preset_summary(preset: str) -> dict[str, str]:
    """Cheap introspection of a preset file: returns its target engine + display.

    Avoids the full ``EngineManifest`` validation cost when callers only
    need to surface the engine + display for listings.
    """
    path = _find_preset_path(preset)
    if path is None:
        raise FileNotFoundError(f"No preset {preset!r}")
    with path.open("rb") as f:
        raw = tomllib.load(f)
    return {
        "preset": preset,
        "engine": str(raw.get("name", "?")),
        "display": str(raw.get("display", "")),
    }


def load_manifest(name: str, preset: str | None = None) -> EngineManifest:
    """Load and validate a manifest.

    Without ``preset``, loads the engine baseline ``<name>.toml``. With
    ``preset``, loads ``presets/<preset>.toml`` instead — a self-contained
    manifest tuned for a specific use case.

    Both baseline and preset are looked up in the user config dir first
    (``$XDG_CONFIG_HOME/asiai-inference-server/``) and the bundled package
    dir second. A user file with the same name overrides the bundled one
    and emits a warning at load time.

    The preset is responsible for declaring every field it needs (no merge
    with the baseline).
    """
    if preset is not None:
        path = _find_preset_path(preset)
        if path is None:
            raise FileNotFoundError(
                f"No preset {preset!r} for engine {name!r}; available presets: {list_presets()}"
            )
    else:
        path = _find_manifest_path(name)
        if path is None:
            raise FileNotFoundError(f"No manifest for engine {name!r}")

    with path.open("rb") as f:
        raw = tomllib.load(f)

    manifest = _from_dict(raw, source=str(path))
    if preset is not None:
        if manifest.name != name:
            raise ManifestError(
                f"{path}: preset declares engine {manifest.name!r} but was requested for "
                f"{name!r}; preset .name field must match the engine baseline name."
            )
        # The plist label and pf anchor are the supervision IDENTITY: install
        # writes them from the preset, but stop/uninstall/status resolve the
        # baseline. If a preset drifts them, the service is installed under one
        # label and torn down under another — an orphan daemon. Pin both to the
        # baseline. (The port is NOT pinned: a user preset legitimately runs an
        # engine on a different port, and teardown keys on label + anchor.)
        baseline_path = _find_manifest_path(name)
        if baseline_path is not None:
            with baseline_path.open("rb") as f:
                baseline = _from_dict(tomllib.load(f), source=str(baseline_path))
            for field, got, want in (
                ("plist.name", manifest.plist.name, baseline.plist.name),
                (
                    "firewall.anchor_name",
                    manifest.firewall.anchor_name,
                    baseline.firewall.anchor_name,
                ),
            ):
                if got != want:
                    raise ManifestError(
                        f"{path}: preset {field}={got!r} differs from the {name!r} baseline "
                        f"({want!r}); a preset may tune behaviour but not the supervision "
                        "identity (label / anchor), or install and uninstall desync."
                    )
    return manifest


def _from_dict(raw: dict, *, source: str) -> EngineManifest:
    try:
        binary_raw = raw["binary"]
        plist_raw = raw["plist"]
        net_raw = raw["network"]
        fw_raw = raw["firewall"]
        log_raw = raw["logs"]
        wrap_raw = raw["wrapper"]
        env_raw = raw.get("environment", {})
        opt_raw = raw.get("options", {})

        manifest = EngineManifest(
            name=raw["name"],
            display=raw["display"],
            binary=BinarySpec(
                candidates=tuple(binary_raw["candidates"]),
                process_pattern=binary_raw["process_pattern"],
                program_args=tuple(binary_raw.get("program_args", [])),
                builds_from_source=bool(binary_raw.get("builds_from_source", False)),
                model_path=binary_raw.get("model_path"),
                template_path=binary_raw.get("template_path"),
                mmproj_path=binary_raw.get("mmproj_path"),
            ),
            plist=PlistSpec(
                name=plist_raw["name"],
                throttle_interval=int(plist_raw["throttle_interval"]),
                timeout=int(plist_raw["timeout"]),
            ),
            network=NetworkSpec(
                port=int(net_raw["port"]),
                bind=str(net_raw.get("bind", "")),
                health_endpoint=net_raw["health_endpoint"],
                health_timeout=int(net_raw["health_timeout"]),
                gen_check=bool(net_raw.get("gen_check", False)),
            ),
            firewall=FirewallSpec(
                supported=bool(fw_raw["supported"]),
                anchor_name=fw_raw["anchor_name"],
            ),
            logs=LogSpec(
                dir=log_raw["dir"],
                stdout=log_raw["stdout"],
                stderr=log_raw["stderr"],
            ),
            wrapper=WrapperSpec(
                needed=bool(wrap_raw["needed"]),
                install_path=wrap_raw.get("install_path"),
                template=wrap_raw.get("template"),
            ),
            env_vars=tuple(env_raw.get("vars", [])),
            options=dict(opt_raw),
        )
    except KeyError as e:
        raise ManifestError(f"{source}: missing required key {e}") from e
    except (TypeError, ValueError) as e:
        if isinstance(e, ManifestError):
            raise
        raise ManifestError(f"{source}: invalid field value ({e})") from e

    _validate(manifest, source=source)
    return manifest


def _validate(m: EngineManifest, *, source: str) -> None:
    if not PLIST_LABEL_RE.match(m.plist.name):
        raise ManifestError(
            f"{source}: plist.name {m.plist.name!r} does not match com.asiai.<engine>; "
            "this is required so the strict-scope sudoers rule still applies."
        )

    if not ANCHOR_NAME_RE.match(m.firewall.anchor_name):
        raise ManifestError(
            f"{source}: firewall.anchor_name {m.firewall.anchor_name!r} must match "
            "com.asiai.<engine> so pfctl wildcard sudoers stays scoped."
        )

    if not (1 <= m.network.port <= 65535):
        raise ManifestError(f"{source}: network.port {m.network.port} out of range")

    if not m.network.health_endpoint.startswith("/"):
        raise ManifestError(
            f"{source}: network.health_endpoint must start with '/', "
            f"got {m.network.health_endpoint!r}"
        )

    if m.wrapper.needed and not m.wrapper.install_path:
        raise ManifestError(f"{source}: wrapper.needed=true but wrapper.install_path is empty")

    if not m.binary.candidates:
        raise ManifestError(f"{source}: binary.candidates is empty")

    if not PROCESS_PATTERN_RE.match(m.binary.process_pattern):
        raise ManifestError(
            f"{source}: binary.process_pattern {m.binary.process_pattern!r} contains "
            "characters that pgrep/pkill -f would interpret as regex metacharacters; "
            "only alphanumerics, '/', '_', '-', '.', and spaces are allowed, with "
            "a leading letter."
        )

    for var in m.env_vars:
        if "=" not in var:
            raise ManifestError(f"{source}: environment.vars entry {var!r} must be 'KEY=VALUE'")


def is_valid_plist_label(label: str) -> bool:
    """Public predicate used by ais_core.sudoers and ais_core.lifecycle."""
    return bool(PLIST_LABEL_RE.match(label))
